version: "master-{build}"

os: Previous Visual Studio 2015
platform:
  - x64

environment:
  matrix:
    - ruby_version: "23-x64"
    - ruby_version: "23"

clone_folder: c:\projects\bundler
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

install:
  - systeminfo
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - SET BUNDLE_WITHOUT=server:docgen:maintenance:pry:travis:integration:ci
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem -FileName C:\cacert.pem
  - set SSL_CERT_FILE=C:\cacert.pem
  - bundle env

build_script:
  - bundle install || bundle install || bundle install

test_script:
  - SET SPEC_OPTS=--format progress
  - bundle exec rake spec
